---
- name: Restart apache
  systemd:
    name: apache2.service
    state: restarted
  become: yes

- name: Reload apache
  systemd:
    name: apache2.service
    state: reloaded
  become: yes

- name: Restart fpm
  systemd:
    name: '{{ item }}-fpm'
    state: restarted
    enabled: yes
  become: yes
  loop: '{{ php_versions }}'
