namespace: kompetenzbolzen
name: stuff
version: 0.21.11
readme: README.md
authors:
- Jonas Gunz <himself@jonasgunz.de>
- Konstantin Grabmann <grbmn@kstn.in>

description: Collections of Ansible roles I use
license_file: 'LICENSE'
tags:
  - certificates
  - webserver
  - database

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies:
  community.general: '>=3.6.0'
  community.crypto: '>=1.8.0'
#build_ignore: []

